name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: Deploy to gh-pages branch
        run: |
          # Configura o git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Adiciona e commita os arquivos gerados
          git add -f build
          git commit -m "Deploy to GitHub Pages"

          # Cria a branch gh-pages se ela não existir e faz o push do conteúdo
          git push origin `git subtree split --prefix build main`:gh-pages --force
